# base docker images with necessary packages installed
FROM docker AS base
ARG DIR=/root/pytope

# install base packages
RUN apk add --no-cache --update \
      py3-pip \
      npm \
      tmux \
      git

# pull down latest code from repository (main branch)
RUN git clone https://docker_img_env:UnpyVDQNqzktj2qUFB6i@gitlab.com/haydenlhannappel/python-test-environment.git $DIR && \
    cd $DIR && \
    pip3 install -r ./server/requirements.txt && \
    cd app && \
    npm install

# declare env variables in container
ENV FLASK_APP=server
ENV PYTOPE_ENV=prod
ENV PYTOPE_DIR=$DIR
EXPOSE 3000

# copy boot script and make executable
COPY boot.sh /tmp/
RUN chmod +x /tmp/boot.sh && \
    echo set -g mouse on > ~/.tmux.conf

CMD ["sh", "-c", "$PYTOPE_DIR/boot.sh"]
