# base docker images with necessary packages installed
FROM docker AS base
ARG DIR=/root/pytope

# install base packages
RUN apk add --no-cache --update \
      py3-pip \
      npm \
      tmux

# copy entire application into image
COPY . $DIR
RUN cd $DIR && \
    # make boot script executable and configure tmux
    chmod +x $DIR/boot.sh && \
    echo set -g mouse on > ~/.tmux.conf && \ 
    # install react dependencies
    cd $DIR/app && \
    npm install && \
    # install python dependencies
    cd $DIR/server && \
    pip3 install -r requirements.txt

# create volume for node_modules so that the container version is used
VOLUME $DIR/app/node_modules

# declare env variables in container
ENV FLASK_APP=server
ENV PYTOPE_ENV=dev
ENV PYTOPE_DIR=$DIR
EXPOSE 3000

ENTRYPOINT ["sh", "-c", "$PYTOPE_DIR/boot.sh"]
